name: 文件
description: 發現文章有錯字或寫得不夠清楚的地方嗎？
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open an issue and help make the docs better.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: |
        Why should we update our docs?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: |
        What should we do instead?
    validations:
      required: true
